### ISSUE TITLE
Crashes when having multiple dynamic keys

### ISSUE THREAD

**Issue by shirotech** [mthadley/eslint-plugin-sort-destructure-keys#20] opened 2019-07-22 14:42 UTC
e.g.

```js
const {[foo]: bar, [one]: two} = props;
```

The expected behaviour is to ignore these, the parser fails when we use dynamic keys.

**Comment by mthadley** [comment] 2019-08-12 04:14
@shirotech Thanks for reporting this!

Do you know which parser [you have configured?](https://eslint.org/docs/user-guide/configuring#specifying-parser)

**Comment by shirotech** [comment] 2019-08-12 04:41
Thanks @mthadley for getting back to me. I am using the `babel-eslint` parser.

**Comment by mthadley** [comment] 2019-08-12 04:53
Gotcha. I only have test coverage for the default ESLint parser (Espree). When I have time I'll try to add coverage for babel-eslint, and hopefully get this plugin working on both.

**Comment by shirotech** [comment] 2019-08-12 05:05
Awesome stuff, thanks for looking into this.

**Comment by mthadley** [comment] 2019-08-18 02:16
@shirotech Which version of `babel-eslint` are you using? I tried with the most recent version, and wasn't able to reproduce.

**Comment by ilich-x** [comment] 2020-04-17 14:26
@mthadley
Hi. I have the same kind of error, when i use computed properties:
```javascript
const {
      [global.MODULE_1]: module1,
      [global.MODULE_2]: module2,
    } = modules;
```
Error: 
```
TypeError: Cannot read property 'name' of undefined
Occurred while linting .../TaskUpdate/components/TaskDetails/index.js:45
  at getNodeName (.../node_modules/eslint-plugin-sort-destructure-keys/lib/rules/sort-destructure-keys.js:21:28)
  at .../node_modules/eslint-plugin-sort-destructure-keys/lib/rules/sort-destructure-keys.js:106:36
  at ObjectPattern (.../node_modules/eslint-plugin-sort-destructure-keys/lib/rules/sort-destructure-keys.js:187:27)
```

but it works if i use template strings
```javascript
const {
      [${global.MODULE_1}`]: module1,
      [${global.MODULE_2}`]: module2,
    } = modules;
```

parser: `babel-eslint: 10.0.3`
eslint: `6.8.0`

**Comment by mthadley** [comment] 2020-04-17 17:01
@ilich-x @shirotech Released a fix for this in `eslint-plugin-sort-destructure-keys@1.3.4`. Do you still the error?

**Comment by ilich-x** [comment] 2020-04-20 09:32
@mthadley it seems to be working for my case, thanx!

**Closed** 2020-04-20 14:10 UTC
