### ISSUE TITLE
Throws error on dynamic destrcturing keys.

### ISSUE THREAD

**Issue by ckruppe** [mthadley/eslint-plugin-sort-destructure-keys#232] opened 2023-04-25 17:06 UTC
The rule throws an error on dynamic key destructuring like so.

```javascript
const {prop1, prop2, [propkey1]: prop3, [propkey2]: prop4} = object;
```

Whole eslint chokes on this line if sort-destructure-keys is active.

**Comment by ckruppe** [comment] 2023-04-25 17:09
The problem is this line:
https://github.com/mthadley/eslint-plugin-sort-destructure-keys/blob/master/lib/rules/sort-destructure-keys.js#L57

Because node.key is undefined in this case.

**Comment by mthadley** [comment] 2023-04-29 20:19
Looks like we have [test coverage for computed properties](https://github.com/mthadley/eslint-plugin-sort-destructure-keys/blob/ccb0d52cb48a55668aff209e1cec4197a16bd23b/tests/lib/rules/sort-destructure-keys.js#L229). I tried copying your example code into the tests, but didn't observe any errors.

@ckruppe Any other info you can provide, like which version of `eslint` you are running? Are you using a parser other than `espree` or `@babel/eslint-parser`?

**Comment by ckruppe** [comment] 2023-07-21 18:42
Sorry for the really late answer but did see the notification only now.
Yes we use @typescript-eslint/parser. Unfortunately i don't have much more information, only what i have provided so far. If there is something i can do to get more information or a place you want me to look or try i am happy to help.

**Comment by mthadley** [comment] 2023-07-22 01:03
@ckruppe No problem on the delayed response.

I took a look at reproducing errors with the code snippet you shared and `@typescript-eslint/parser`, but didn't have any luck. [You can see the branch here](https://github.com/mthadley/eslint-plugin-sort-destructure-keys/compare/master...ts-eslint-parser), which has all tests passing using that parser.

Let me know if there's any additional context you can provide, as otherwise I can't reproduce the issue.

**Comment by mthadley** [comment] 2024-04-24 03:53
Closing since it has been a while, but folks can open a new issue with more information if it is still happening.

**Closed by mthadley** 2024-04-24 03:53 UTC
Labels: bug
